---

- name: install sssd
  action: apt pkg=$item state=installed
  with_items:
    - sssd
    - libsss-sudo0
  tags: sssd

- name: ensure sssd.conf exists
  template: src=etc/sssd/sssd.conf.j2 dest=/etc/sssd/sssd.conf owner=root group=root mode=0600
  notify:
    - restart sssd
  tags: sssd

- name: ensure sssd is started
  service: name=sssd state=started
  tags: sssd
